### ISSUE TITLE
MB: Enhanced Cover Art Uploads | t.finally is not a function | Waterfox 2022.06

### ISSUE THREAD

**Issue by tordenflesk** [ROpdebee/mb-userscripts#537]
Reverted to last known working version 20 of the script. 22.7.27.4.
![image](https://user-images.githubusercontent.com/2136727/181864667-8263e845-ad0c-4eae-9a95-093a5950d15d.png)

**Comment by ROpdebee** [comment]
Yeah this is something introduced by #516. I'll rewrite it to not use `Promise.finally` directly because I don't like forcing users of recent browsers to use an old version of the script and not be able to update.

**Comment by ROpdebee** [comment]
@tordenflesk could you try the version in https://github.com/ROpdebee/mb-userscripts/pull/542#issuecomment-1203929407 and see if that fixes it for you?

**Comment by tordenflesk** [comment]
No error, appears to be working fine.
